CREATE TABLE `products` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `bar_code` varchar(255) DEFAULT NULL,
   `cost_price` double DEFAULT NULL,
   `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `description` varchar(255) DEFAULT NULL,
   `device_id` bigint(20) NOT NULL,
   `hide` tinyint(1) NOT NULL DEFAULT '0',
   `price` double DEFAULT NULL,
   `product_id` varchar(255) NOT NULL,
   `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `with_point_system` int(11) NOT NULL,
   `with_pos` int(11) NOT NULL,
   `with_tax` tinyint(1) NOT NULL DEFAULT '1',
   `display_name` varchar(255) DEFAULT NULL,
   `in_stock` tinyint(1) NOT NULL DEFAULT '0',
   `manage_stock` tinyint(1) NOT NULL DEFAULT '0',
   `regular_price` double NOT NULL,
   `sale_price` double NOT NULL,
   `sku` varchar(255) DEFAULT NULL,
   `status` varchar(255) NOT NULL DEFAULT 'ACTIVE',
   `stock_quantity` int(11) NOT NULL,
   `branch_id` bigint(20) DEFAULT '1',
   `by_employee` bigint(20) DEFAULT NULL,
   `category_id` bigint(20) DEFAULT NULL,
   `unit` varchar(255) DEFAULT 'QUANTITY',
   `weight` double NOT NULL,
   `product_code` varchar(255) DEFAULT NULL,
   `offer_id` varchar(255) DEFAULT NULL,
   `last_cost_price_inventory` double DEFAULT '0',
   `manual_cost_price` double DEFAULT '0',
   `with_serial_number` tinyint(1) DEFAULT '0',
   `currency_type` varchar(255) DEFAULT 'ILS',
   `price_with_out_tax` double DEFAULT '0',
   `price_with_tax` double DEFAULT '0',
   PRIMARY KEY (`id`),
   KEY `index5` (`device_id`)
 ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `products` (`bar_code`,`cost_price`,`description`,`device_id`,`hide`,`price`,`product_id`,`with_point_system`,`with_pos`,`with_tax`,`display_name`,`in_stock`,`manage_stock`,`regular_price`,`sale_price`,`sku`,`status`,`stock_quantity`,`branch_id`,`by_employee`,`category_id`,`unit`,`weight`,`product_code`,`offer_id`,`last_cost_price_inventory`,`manual_cost_price`,`with_serial_number`,`currency_type`,`price_with_out_tax`,`price_with_tax`) VALUES ('0',0,'general',0,0,0,'-1',0,0,1,'general',0,0,0,0,'0','ACTIVE',0,0,NULL,1,'QUANTITY',0,'general',NULL,0,0,0,'ILS',0,0);
