CREATE TABLE `products` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `bar_code` varchar(255) DEFAULT NULL,
   `cost_price` double DEFAULT NULL,
   `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `description` varchar(255) DEFAULT NULL,
   `device_id` bigint(20) NOT NULL,
   `hide` tinyint(1) NOT NULL DEFAULT '0',
   `name` varchar(255) DEFAULT NULL,
   `price` double DEFAULT NULL,
   `product_id` varchar(255) NOT NULL,
   `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `with_point_system` int(11) NOT NULL,
   `with_pos` int(11) NOT NULL,
   `with_tax` tinyint(1) NOT NULL DEFAULT '1',
   `display_name` varchar(255) DEFAULT NULL,
   `in_stock` tinyint(1) NOT NULL DEFAULT '0',
   `manage_stock` tinyint(1) NOT NULL DEFAULT '0',
   `regular_price` double NOT NULL,
   `sale_price` double NOT NULL,
   `sku` varchar(255) DEFAULT NULL,
   `status` varchar(255) NOT NULL DEFAULT 'ACTIVE',
   `stock_quantity` int(11) NOT NULL,
   `branch_id` bigint(20) DEFAULT '1',
   `by_employee` bigint(20) DEFAULT NULL,
   `category_id` bigint(20) DEFAULT NULL,
   `unit` varchar(255) DEFAULT 'QUANTITY',
   `weight` double NOT NULL,
   `product_code` varchar(255) DEFAULT NULL,
   `offer_id` varchar(255) DEFAULT NULL,
   `last_cost_price_inventory` double DEFAULT '0',
   `manual_cost_price` double DEFAULT '0',
   `with_serial_number` tinyint(1) DEFAULT '0',
   `currency_type` varchar(255) DEFAULT 'ILS',
   `price_with_out_tax` double DEFAULT '0',
   `price_with_tax` double DEFAULT '0',
   PRIMARY KEY (`id`),
   UNIQUE KEY `u` (`product_id`,`branch_id`),
   UNIQUE KEY `productUniqueSku` (`sku`,`branch_id`),
   UNIQUE KEY `productUniqueName` (`branch_id`,`product_code`),
   KEY `index5` (`device_id`)
 ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;